replicaCount: 1

fullnameOverride: leader

config:
  scName: standard-rwo
  license:
  token:
  adminPassword: admin
  rejectSelfSignedCerts: 0

service:
  internalType: ClusterIP
  externalType: LoadBalancer
  annotations:
    cloud.google.com/l4-rbs: "enabled"
    cloud.google.com/network-tier: "Standard"
  ports:
  - name: api
    port: 9000
    protocol: TCP
    external: true
  - name: leadercomm
    port: 4200
    protocol: TCP
    external: true
